# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: historiographer 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "historiographer"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["brettshollenberger"]
  s.date = "2016-11-28"
  s.description = "Creates separate tables for each history table"
  s.email = "brett.shollenberger@gmail.com"
  s.homepage = "http://github.com/instacart/historiographer"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Create histories of your ActiveRecord tables"
end

