# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: historiographer 4.4.5 ruby lib

Gem::Specification.new do |s|
  s.name = "historiographer".freeze
  s.version = "4.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["brettshollenberger".freeze]
  s.date = "2026-01-14"
  s.description = "Creates separate tables for each history table".freeze
  s.email = "brett.shollenberger@gmail.com".freeze
  s.executables = ["console".freeze, "setup".freeze, "test".freeze, "test-all".freeze, "test-rails".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "DEVELOPMENT.md",
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/console",
    "bin/setup",
    "bin/test",
    "bin/test-all",
    "bin/test-rails",
    "historiographer.gemspec",
    "init.rb",
    "instructions/implementation.md",
    "instructions/todo.md",
    "lib/historiographer.rb",
    "lib/historiographer/configuration.rb",
    "lib/historiographer/history.rb",
    "lib/historiographer/history_migration.rb",
    "lib/historiographer/history_migration_mysql.rb",
    "lib/historiographer/mysql_migration.rb",
    "lib/historiographer/postgres_migration.rb",
    "lib/historiographer/relation.rb",
    "lib/historiographer/safe.rb",
    "lib/historiographer/silent.rb",
    "lib/historiographer/version.rb",
    "spec/combustion_helper.rb",
    "spec/db/database.yml",
    "spec/db/migrate/20161121212228_create_posts.rb",
    "spec/db/migrate/20161121212229_create_post_histories.rb",
    "spec/db/migrate/20161121212230_create_authors.rb",
    "spec/db/migrate/20161121212231_create_author_histories.rb",
    "spec/db/migrate/20161121212232_create_users.rb",
    "spec/db/migrate/20171011194624_create_safe_posts.rb",
    "spec/db/migrate/20171011194715_create_safe_post_histories.rb",
    "spec/db/migrate/20191024142304_create_thing_with_compound_index.rb",
    "spec/db/migrate/20191024142352_create_thing_with_compound_index_history.rb",
    "spec/db/migrate/20191024203106_create_thing_without_history.rb",
    "spec/db/migrate/20221018204220_create_silent_posts.rb",
    "spec/db/migrate/20221018204255_create_silent_post_histories.rb",
    "spec/db/migrate/20241109182017_create_comments.rb",
    "spec/db/migrate/20241109182020_create_comment_histories.rb",
    "spec/db/migrate/20241119000000_create_datasets.rb",
    "spec/db/migrate/2025082100000_create_projects.rb",
    "spec/db/migrate/2025082100001_create_project_files.rb",
    "spec/db/migrate/20250823000000_create_easy_ml_columns.rb",
    "spec/db/migrate/20250824000000_create_test_articles.rb",
    "spec/db/migrate/20250824000001_create_test_categories.rb",
    "spec/db/migrate/20250825000000_create_bylines.rb",
    "spec/db/migrate/20250826000000_create_test_users.rb",
    "spec/db/migrate/20250826000001_create_test_user_histories.rb",
    "spec/db/migrate/20250826000002_create_test_websites.rb",
    "spec/db/migrate/20250826000003_create_test_website_histories.rb",
    "spec/db/migrate/20250827000000_create_templates.rb",
    "spec/db/migrate/20250827000001_create_template_histories.rb",
    "spec/db/migrate/20250827000002_create_websites.rb",
    "spec/db/migrate/20250827000003_create_website_histories.rb",
    "spec/db/migrate/20250827000004_create_template_files.rb",
    "spec/db/migrate/20250827000005_create_template_file_histories.rb",
    "spec/db/migrate/20250827000006_create_website_files.rb",
    "spec/db/migrate/20250827000007_create_website_file_histories.rb",
    "spec/db/migrate/20250827000008_create_code_files_view.rb",
    "spec/db/schema.rb",
    "spec/examples.txt",
    "spec/factories/post.rb",
    "spec/historiographer_spec.rb",
    "spec/integration/historiographer_safe_integration_spec.rb",
    "spec/internal/app/models/application_record.rb",
    "spec/internal/app/models/deploy.rb",
    "spec/internal/app/models/user.rb",
    "spec/internal/app/models/website.rb",
    "spec/internal/app/models/website_history.rb",
    "spec/internal/config/database.yml",
    "spec/internal/config/routes.rb",
    "spec/internal/db/schema.rb",
    "spec/internal/log/development.log",
    "spec/internal/log/test.log",
    "spec/models/application_record.rb",
    "spec/models/author.rb",
    "spec/models/author_history.rb",
    "spec/models/byline.rb",
    "spec/models/code_file.rb",
    "spec/models/comment.rb",
    "spec/models/comment_history.rb",
    "spec/models/easy_ml/column.rb",
    "spec/models/easy_ml/column_history.rb",
    "spec/models/post.rb",
    "spec/models/post_history.rb",
    "spec/models/project.rb",
    "spec/models/project_file.rb",
    "spec/models/project_file_history.rb",
    "spec/models/project_history.rb",
    "spec/models/safe_post.rb",
    "spec/models/safe_post_history.rb",
    "spec/models/silent_post.rb",
    "spec/models/silent_post_history.rb",
    "spec/models/template.rb",
    "spec/models/template_file.rb",
    "spec/models/template_file_history.rb",
    "spec/models/template_history.rb",
    "spec/models/test_article.rb",
    "spec/models/test_article_history.rb",
    "spec/models/test_category.rb",
    "spec/models/test_category_history.rb",
    "spec/models/test_user.rb",
    "spec/models/test_user_history.rb",
    "spec/models/test_website.rb",
    "spec/models/test_website_history.rb",
    "spec/models/thing_with_compound_index.rb",
    "spec/models/thing_with_compound_index_history.rb",
    "spec/models/thing_without_history.rb",
    "spec/models/user.rb",
    "spec/models/website.rb",
    "spec/models/website_file.rb",
    "spec/models/website_file_history.rb",
    "spec/models/website_history.rb",
    "spec/rails_integration/historiographer_rails_integration_spec.rb",
    "spec/spec_helper.rb",
    "spec/view_backed_model_spec.rb"
  ]
  s.homepage = "http://github.com/brettshollenberger/historiographer".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.2.22".freeze
  s.summary = "Create histories of your ActiveRecord tables".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<activerecord>.freeze, [">= 6"])
    s.add_runtime_dependency(%q<activerecord-import>.freeze, [">= 0"])
    s.add_runtime_dependency(%q<activesupport>.freeze, [">= 0"])
    s.add_runtime_dependency(%q<rails>.freeze, [">= 6"])
    s.add_development_dependency(%q<mysql2>.freeze, ["= 0.5"])
    s.add_development_dependency(%q<paranoia>.freeze, [">= 0"])
    s.add_development_dependency(%q<pg>.freeze, [">= 0"])
    s.add_development_dependency(%q<pry>.freeze, [">= 0"])
    s.add_development_dependency(%q<standalone_migrations>.freeze, [">= 0"])
    s.add_development_dependency(%q<timecop>.freeze, [">= 0"])
    s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
  else
    s.add_dependency(%q<activerecord>.freeze, [">= 6"])
    s.add_dependency(%q<activerecord-import>.freeze, [">= 0"])
    s.add_dependency(%q<activesupport>.freeze, [">= 0"])
    s.add_dependency(%q<rails>.freeze, [">= 6"])
    s.add_dependency(%q<mysql2>.freeze, ["= 0.5"])
    s.add_dependency(%q<paranoia>.freeze, [">= 0"])
    s.add_dependency(%q<pg>.freeze, [">= 0"])
    s.add_dependency(%q<pry>.freeze, [">= 0"])
    s.add_dependency(%q<standalone_migrations>.freeze, [">= 0"])
    s.add_dependency(%q<timecop>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

