development:
  adapter: postgresql
  encoding: unicode
  database: historiographer_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: historiographer_test
  pool: 5

# mysql_default: &mysql_default
#   adapter: mysql2
#   encoding: utf8
#   username: root
#   password:
#   host: 127.0.0.1
#   port: 3306

# development:
#   <<: *mysql_default
#   database: historiographer_development

# test:
#   <<: *mysql_default
#   database: historiographer_test
